@echo off
:: ShadowFile — Windows launcher
:: Double-click this file, or run:  start.bat
:: For stronger AI:                 start.bat --strong

title ShadowFile

:: ── Model selection ───────────────────────────────────────────────────────────
set OLLAMA_MODEL=llama3.2
set MODEL_LABEL=llama3.2:3b (fast, ~2 GB)

echo %* | findstr /i "\-\-strong" >nul 2>&1
if not errorlevel 1 (
    set OLLAMA_MODEL=llama3.1:8b
    set MODEL_LABEL=llama3.1:8b (stronger, ~5 GB)
)

echo.
echo ShadowFile
echo AI model: %MODEL_LABEL%
echo ────────────────────────────────
echo.

:: ── 1. Node.js ───────────────────────────────────────────────────────────────
where node >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Node.js not found.
    echo.
    echo   Install from: https://nodejs.org  ^(choose LTS^)
    echo   Then double-click start.bat again.
    echo.
    start https://nodejs.org
    pause
    exit /b 1
)
for /f "tokens=*" %%v in ('node -v') do echo [OK] Node.js %%v

:: ── 2. npm install ───────────────────────────────────────────────────────────
if not exist "node_modules\" (
    echo [->] Installing dependencies ^(first run, ~1 min^)...
    call npm install --silent
)
echo [OK] Dependencies ready

:: ── 3. Ollama ────────────────────────────────────────────────────────────────
where ollama >nul 2>&1
if errorlevel 1 (
    echo.
    echo [WARN] Ollama not found.
    echo.
    echo   Ollama runs the AI locally — no API key, no token limits.
    echo   Opening https://ollama.com to download...
    echo   After installing, double-click start.bat again.
    echo.
    start https://ollama.com
    pause
    exit /b 0
)
echo [OK] Ollama found

:: ── 4. Start Ollama daemon ───────────────────────────────────────────────────
curl -s http://localhost:11434 >nul 2>&1
if errorlevel 1 (
    echo [->] Starting Ollama...
    start /b ollama serve
    timeout /t 3 /nobreak >nul
)
echo [OK] Ollama running

:: ── 5. Pull model ────────────────────────────────────────────────────────────
ollama list | findstr /i "%OLLAMA_MODEL%" >nul 2>&1
if errorlevel 1 (
    echo [->] Pulling model: %MODEL_LABEL%
    echo      This downloads once and is cached.
    ollama pull %OLLAMA_MODEL%
)
echo [OK] Model ready: %OLLAMA_MODEL%

:: ── 6. Write .env.local ──────────────────────────────────────────────────────
if not exist ".env.local" (
    (
        echo # Auto-generated by start.bat
        echo OLLAMA_BASE_URL=http://localhost:11434/v1
        echo OLLAMA_MODEL=%OLLAMA_MODEL%
    ) > .env.local
    echo [OK] .env.local created
) else (
    powershell -Command "(gc .env.local) -replace '^OLLAMA_MODEL=.*','OLLAMA_MODEL=%OLLAMA_MODEL%' -replace '^OLLAMA_BASE_URL=.*','OLLAMA_BASE_URL=http://localhost:11434/v1' | Set-Content .env.local"
    echo [OK] .env.local updated
)

:: ── 7. Launch ────────────────────────────────────────────────────────────────
echo.
echo Starting ShadowFile...
echo   ^> http://localhost:5173
echo   Press Ctrl+C to stop.
echo.

:: Open browser after delay
start "" cmd /c "timeout /t 3 /nobreak >nul & start http://localhost:5173"

call npm run dev
pause
